from defpi.Connection import Connection
from defpi.Service import Service

from .InflexibleControllerConnectionManager import InflexibleControllerConnectionManager
from .vEfi20.InflexibleControllerEfi20ConnectionHandler import InflexibleControllerEfi20ConnectionHandler
from .vEfi20.InflexibleControllerEfi20ConnectionHandlerImpl import InflexibleControllerEfi20ConnectionHandlerImpl


class InflexibleControllerConnectionManagerImpl(InflexibleControllerConnectionManager):
    """ InflexibleControllerConnectionManagerImpl
        Manages all connection handlers for the Universal Dimmer service
        Generated by Python code generator for dEF-Pi at May 31, 2018, 9:34:25 AM by maarten

        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin 
        will not change the contents of this file.

        Template by FAN, 2017 """

    def __init__(self, service: Service):
        """ Auto-generated constructor building the manager for the provided service """
        self.service = service

    def buildEfi20(self, connection: Connection) -> InflexibleControllerEfi20ConnectionHandler:
        """ Build version vEfi20 of the connection handler """
        return InflexibleControllerEfi20ConnectionHandlerImpl(connection, self.service)

