from abc import abstractmethod

from defpi.ConnectionHandlerManager import ConnectionHandlerManager

from .vEfi20.InflexibleControllerEfi20ConnectionHandler import InflexibleControllerEfi20ConnectionHandler


class InflexibleControllerConnectionManager(ConnectionHandlerManager):
    """ InflexibleControllerConnectionManager
        Abstract base class for connection handler manager
        Generated by Python code generator for dEF-Pi at May 31, 2018, 9:34:25 AM by maarten

        NOTE: This file will be overwritten when the code generator is re-run; any user-made changes will be removed.

        Template by FAN, 2017 """

    @abstractmethod
    def build_inflexible_controller_efi_20(self, connection) -> InflexibleControllerEfi20ConnectionHandler: raise NotImplementedError

