version: "3"
networks:
  management:
    driver: overlay
services:
  orchestrator:
    image: flexiblepower/defpi-orchestrator:17.11
    ports:
      - 8484:8080
      - 9999:9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mongo_test
    networks:
      - management
    environment:
      - JVM_ARGUMENTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n
      - MONGO_HOST=mongo_test
      - MONGO_DATABASE=def-pi
      - MONGO_PORT=27017
      - REGISTRY_URL=${REGISTRY_URL}:5000
      - USE_SECURE_REGISTRY=false
  orchestrator-ui:
    image: flexiblepower/defpi-orchestrator:17.11
    ports:
      - 84:80
    environment:
      - ORCHESTRATOR_URL=http://127.0.0.1:8484/
  registry:
    image: registry:2
    ports:
      - 5000:5000
  mongo_test:
    image: mvertes/alpine-mongo
    ports:
      - 0.0.0.0:27017:27017
    networks:
      - management
