package org.flexiblepower.defpi.lightsimulator.observation_publisher;

import javax.annotation.Generated;

import org.flexiblepower.defpi.lightsimulator.LightSimulator;
import org.flexiblepower.defpi.lightsimulator.observation_publisher._1.ObservationPublisher_1ConnectionHandler;
import org.flexiblepower.defpi.lightsimulator.observation_publisher._1.ObservationPublisher_1ConnectionHandlerImpl;
import org.flexiblepower.service.Connection;

/**
 * ObservationPublisherConnectionManagerImpl
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author coenvl
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Nov 8, 2017 4:10:46 PM")
public class ObservationPublisherConnectionManagerImpl implements ObservationPublisherConnectionManager {

	private final LightSimulator service;
	
	/**
	 * Auto-generated constructor building the factory for ConnectionHandlers of the provided service
	 *
	 * @param service The service that will be used as argument to instantiate the ConnectionHandlers
	 */
	public ObservationPublisherConnectionManagerImpl(LightSimulator service) {
		this.service = service;
	}

	@Override
	public ObservationPublisher_1ConnectionHandler build1(Connection connection) {
		return new ObservationPublisher_1ConnectionHandlerImpl(connection, this.service);
	}

}

