package org.flexiblepower.defpi.lightsimulator.inflexible_controller.minimal_efi_20;

import javax.annotation.Generated;

import org.flexiblepower.defpi.lightsimulator.LightSimulator;
import org.flexiblepower.defpi.lightsimulator.inflexible_controller.efi_20.xml.InflexibleInstruction;
import org.flexiblepower.service.Connection;

/**
 * InflexibleController_minimalEfi20ConnectionHandlerImpl
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author coenvl
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Nov 8, 2017 4:10:46 PM")
public class InflexibleController_minimalEfi20ConnectionHandlerImpl implements InflexibleController_minimalEfi20ConnectionHandler {

	private final Connection connection;

	private final LightSimulator service;

	/**
	 * Auto-generated constructor for the ConnectionHandlers of the provided service
	 *
	 * @param service The service for which to handle the connections
	 */
	public InflexibleController_minimalEfi20ConnectionHandlerImpl(Connection connection, LightSimulator service) {
		this.connection = connection;
		this.service = service;
	}

	@Override
	public void handleInflexibleInstructionMessage(InflexibleInstruction message) {
		// TODO Auto-generated stub
		
	}

	@Override
	public void onSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void terminated() {
		// TODO Auto-generated method stub
		
	}

}