from abc import abstractmethod

from defpi.ConnectionHandler import ConnectionHandler, InterfaceInfo


class InflexibleControllerEfi20ConnectionHandler(ConnectionHandler):
    """ InflexibleControllerEfi20ConnectionHandler
        Abstract base class for connection handlers
        Generated by Python code generator for dEF-Pi at May 31, 2018, 9:34:25 AM by maarten

        NOTE: This file will be overwritten when the code generator is re-run; any user-made changes will be removed.

        Template by FAN, 2017 """

    interfaceInfo = InterfaceInfo(name="Inflexible Controller",
                                  version="efi 2.0",
                                  receivesHash="6f85a6fd68a3ad9ab675848cf3a7dc31e5a87e8678435ec6dc847119504e5587",
                                  sendsHash="31fffa222831723a1b2ceaec406ed47140029d3230971c953b8857946a8fa89a",
                                  serializer="xsd")

    @abstractmethod
    def handleInflexibleRegistrationMessage(self, message): raise NotImplementedError


    @abstractmethod
    def handleInflexibleCurtailmentOptionsMessage(self, message): raise NotImplementedError


    @abstractmethod
    def handleMeasurementMessage(self, message): raise NotImplementedError

