package org.flexiblepower.defpi.lightsimulator;

import java.io.Serializable;

import javax.annotation.Generated;

import org.flexiblepower.service.DefPiParameters;
import org.flexiblepower.service.Service;

/**
 * LightSimulator provides an implementation of the Light Simulator service
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author coenvl
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Nov 8, 2017 4:10:45 PM")
public class LightSimulator implements Service<LightSimulatorConfiguration> {
		
	@Override
	public void resumeFrom(Serializable state) {
		// TODO Auto-generated method stub

	}

	@Override
	public void init(LightSimulatorConfiguration config, DefPiParameters parameters) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void modify(LightSimulatorConfiguration config) {
		// TODO Auto-generated method stub
	}

	@Override
	public Serializable suspend() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void terminate() {
		// TODO Auto-generated method stub
	}
	
}
